# ingress: https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/values.yaml#L169
config:  
  clientID: "<path:kv/data/oauth2proxy#CLIENT_ID>"
  clientSecret: "<path:kv/data/oauth2proxy#CLIENT_SECRET>"
  configFile: |
    provider: "keycloak-oidc"
    oidcIssuerURL: "https://keycloak.cyverse.at/auth/realms/CyVerse"
    cookie_domains = ["<path:kv/data/oauth2proxy#WHITELIST_DOMAIN>"]
    whitelist_domains = ["<path:kv/data/oauth2proxy#WHITELIST_DOMAIN>"]
    upstreams = ["https://argocd-server.argocd.svc.cluster.local:80"]
    
ingress:
  enabled: true
  className: nginx
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  path: /
  pathType: Prefix
  hosts:
    - <path:kv/data/oauth2proxy#HOSTNAME>
  tls: []
