# ingress: https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/values.yaml#L169
envFrom:
  - secretRef:
      name: oauth2proxy-secrets
      
ingress:
  enabled: true
  className: nginx
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  path: /
  pathType: Prefix
  hosts:
    - ${HOSTNAME}
  tls: []

extraArgs:
 - --whitelist-domain=${WHITELIST_DOMAIN}
 - --cookie-domain=${WHITELIST_DOMAIN}
 - --provider=keycloak-oidc
 - --client-id=${CLIENT_ID}
 - --client-secret=${CLIENT_SECRET}
 - --oidc-issuer-url=https://keycloak.cyverse.at/auth/realms/CyVerse
 - --upstream=https://argocd-server.argocd.svc.cluster.local:80
