# ingress: https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/values.yaml#L169
config:  
  provider: "keycloak-oidc"
  clientID: "<path:kv/data/oauth2proxy#CLIENT_ID>"
  clientSecret: "<path:kv/data/oauth2proxy#CLIENT_SECRET>"
  oidcIssuerURL: "https://keycloak.cyverse.at/auth/realms/CyVerse"
  upstreams:
    - "https://argocd-server.argocd.svc.cluster.local:80"
  cookieDomains:
    - "path:kv/data/oauth2proxy#WHITELIST_DOMAIN"
  whitelistDomains:
    - "path:kv/data/oauth2proxy#WHITELIST_DOMAIN"
ingress:
  enabled: true
  className: nginx
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  path: /
  pathType: Prefix
  hosts:
    - <path:kv/data/oauth2proxy#HOSTNAME>
  tls: []
